### ISSUE TITLE
style_override_squirrel 似乎沒有效果

### ISSUE THREAD

**Issue by GJRobert** [danvim/rime-skin-win#2]
@lotem 你好，
我使用了 plum 跑你說的
```bash
$ bash rime-install danvim/rime-theme-windows10:customize:frontend=squirrel
```
代碼都有順利 patch 到 squirrel.custom.yaml 中

但是 `style_override_squirrel` 下面的設定項目，完全都被鼠鬚管無視了，還是套用我原本已有的設定。比方說我還是得手動修改 `style/color_scheme` 為 `windows10`，才能用上這個 theme，而且其他的 style 選項都沒有配套生效，只有顏色變了。

（因為這個功能是你貢獻的，所以我就沒有 tag danvim 了。不好意思最近詢問了很多問題，感謝你的協助！）

**Comment by lotem** [comment]
配方中修改`style`部分的代碼，不能與其他修改`style`的補丁共存。具體地說是應用補丁的順序沒有保證。請檢查一下是不是這個原因。

**Comment by GJRobert** [comment]
好的，行了，我把 squirrel.custom.yaml 裡頭 `style` 開頭的設定都 `#` 註解掉，這樣 `style_override_squirrel` 的效果就出來了。具體而言，我可以保留自己堅持想要的 `style/xxxxxxx` 設定，剩下的才交給 `style_override_squirrel`。

太好了，善用東風破來部署配色主題設定真的是絕招，謝謝你的分享！

**Comment by GJRobert** [comment]
所以，[說明文件](https://github.com/lotem/rime-theme-windows10/blob/master/README.md)裡，或許可以加註說明，squirrel.custom.yaml 或 weasel.custom.yaml 裡頭可以選擇保留哪些 `style` 設定，其餘的才會套用主題內的設定〜
